### ISSUE TITLE
ChatFragment Тосты

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#10]
Тосты- это элементы UI,  его не нужно запускать в треде, причем в таком, который объявляешь ты (requireActivity().runOnUiThread {}) Так вообще не делают. Плюс, ты опять передаешь методу интерфейс, а значит логика интерфейса пишется в момент вызова метода в фигурных скобках. И не нужно выделять тосту переменную, просто Toast.makeText(requireContext(), R.string.request_err, Toast.LENGTH_SHORT).show()  будет достаточно (обрати внимание на requireContext вместо applicationContext.). но по-хорошему в VM заводится singleLiveEventLiveData для сообщений и этот onFailure коллбэк обрабатывается в VM, а не интерфейсом в фрагменте. Сразу в VM методе закидывается сообщение в SingleLiveEvent, а в фрагменте прослушивается, так чище и вернее. Плюс, если ты не передаешь коллбэк в метод, то и сам метод catalogViewModel.loadChats(onRequestError) можно не вызывать из фрагмента. вызываешь этот метод в самом ViewModel из init{} блока. Выглядеть должно так: объявление переменных, далее согласно конвенциям инитблок init { loadChats() }

**Comment by aiko135** [comment]
reworked
