### ISSUE TITLE
ChatFragment Аргументы

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#11]
Аргументы можно передавать и вытягивать явно:

- https://developer.android.com/guide/navigation/navigation-pass-data
- И незачем создавать для них переменные, ты в фрагменте их не используешь. Передавай сразу в VM
- Убрать точки с запятой
`

val chatUuid = arguments?.getString("chatid")        
val userUuid =  arguments?.getString("userid")        
val managerName=  arguments?.getString("managername")        
binding.contactorName.text  = managerName;
chatViewModel.chatid = chatUuid;        
chatViewModel.userid = userUuid;

=====>

 
binding.contactorName.text  =arguments?.getString("managername")    
chatViewModel.chatid = arguments?.getString("chatid")  
chatViewModel.userid = arguments?.getString("userid")   

`

**Comment by aiko135** [comment]
Refactored
