### ISSUE TITLE
Конкатенация строк

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#15]
В GoodGragment увидел такую штуку:
`val url: String = RetrofitClient.IMAGE_DOWNLOAD_URL + '/' + it.good.imgPath;`

В Kotlin это делается так:
`val url = "$RetrofitClient.IMAGE_DOWNLOAD_URL/${it.good.imgPath}"`
Без объявления типа, тут и так ясно, что это строка. Без точки с запятой

**Comment by aiko135** [comment]
Refactored
