### ISSUE TITLE
LoginFragment Observers

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#16]
`
loginViewModel.loginResultLiveData.observe(viewLifecycleOwner, Observer(onRequestResultObserver) )        loginViewModel.user.observe(viewLifecycleOwner, Observer(onUserFound))
`
Это так не пишется, для этого не выделяются переменные, все пишется на месте. У тебя в одном фрагменте так, в другом по-другому. Observer здорового человека представляет из себя что-то такое:
`
with(viewModel) {
listLiveData.observe(viewLifecycleOwner) { list ->
adapter.submitList(list)
}
errorLiveData.observe(viewLifecycleOwner) { message ->
message?.let { toast(it) }
}
}`

Если у тебя несколько обращений за раз, допустим, к биндингу или VM, то можнго обернуть как здесь, в with()

**Comment by aiko135** [comment]
Не очень же удобно в одну строчку обработчик писать. Почему бы не задать проперти функционального типа и присвоить значение в виде лямбды. Так код более понятным как по мне, а так не знаю, фкусовщина. 
private val onRequestResultObserver : (data : LoginResult)->Unit = {...}

**Comment by GordeyevSergey** [comment]
Наоборот, читаемость ухудшается, если выделять под обсерверы переменные и пихать их черт знат куда. Ладно бы еще там была реализация безымянного интерфейса а ля object : Observer { override fun observe...}
Но там лямбда, вместо обсервера скобки фигурные, все просто как три копейки

**Comment by aiko135** [comment]
Refactored. Но в паре мест все же оставил, так как там получается слишком много кода в обсерверах
