### ISSUE TITLE
StartFragment

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#18]
Лишние переменные
`private fun uncheckBottomNav(){       
val bottomNavigation =activity?.findViewById&lt;BottomNavigationView&gt;(R.id.nav_view) ?: return;        
val menu = bottomNavigation.menu;        
menu.setGroupCheckable(0,true,false);        
for (i in 0 until menu.size()) {            
menu.getItem(i).isChecked = false        
}        
menu.setGroupCheckable(0, true, true)    
}
`

Можно записать так:
`private fun uncheckBottomNav(){       
val bottomNavigation =activity?.findViewById&lt;BottomNavigationView&gt;(R.id.nav_view) ?: return;        
with(bottomNavigation.menu) {
setGroupCheckable(0,true,false);        
for (i in 0 until menu.size()) {            
getItem(i).isChecked = false        
}        
setGroupCheckable(0, true, true)    
}
}

и for, скорее всего, можно заменить на forEach{}
menu.forEach { item ->
item.isChecked = false
}
`

**Comment by aiko135** [comment]
Этот код уже удален так как BottomNavigation больше не используется
