### ISSUE TITLE
ProfileFragment When

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#19]
`
when{
u.role.toInt() == 2 ->{role = "Manager";}
u.role.toInt() == 3  ->{role = "Administrator"}
}
`
Ты when используешь как if, а в текущем моменте нужно использовать как switch, плюс, как писал ранее, название переменной "u" - плохое. тотально непонятное
Нормальный when пишется так:
`
role = when(u.role.toInt()){
2 -> "Manager"
3  -> "Administrator"
}
`

**Comment by aiko135** [comment]
Refactored
