### ISSUE TITLE
RegisterFragment

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#21]
`binding.editTextTextPassword.text.toString() == binding.editTextTextPassword3.text.toString()`
Для таких случаев можно писать extention function "private fun EditText.getText() = this.text.toString()"
и выглядеть будет так:
`
with(binding) {
if (editText1.getText() == editText2.getText())
}
`
только в getText() имя поменять, у EditText и так есть геттер getText() (.text)

`var newUser : User = User(...)`
Это уже логика, ее в фрагменте быть не должно. Выкинуть в ViewModel
Ну и все то, что написано про каждый из фрагментов относится ко всем

**Comment by aiko135** [comment]
1.в данном случае var newUser : User = User(...) используется как DTO. Не хочу просто очень много (около 9) параметров функции использовать. 
2. Не хочу расширение лишний раз юзать (для добавления нового метода классу) гараздо проще просто вызвать getText() по ссылке из нужного TextView
