### ISSUE TITLE
Исправить Binding

### ISSUE THREAD

**Issue by GordeyevSergey** [aiko135/uldbsMarket#6]
На всех фрагментах биндинг инитится явно в OnCreateView, заменить на ленивую инициализацию: `private val binding by lazy(LazyThreadSafetyMode.NONE) { YourView.inflate(layoutInflater) }` инит будет происходить в момент первого вызова, только теперь фрагменты будут чище. Убрать lateinit у него, и вообще везде где можно убрать lateinit- лучше убрать. Выглядеть все это дело должно так:  после объявления класса ленивый инит биндинга, а в onCreateView останется только сделать return binding.root. Никаких дополнительных инфлейтов а ля val view = inflater.inflate... В активити тоже поставить биндинг, он будет лучше смотреться чем kotlin syntetic findViewById()

**Comment by aiko135** [comment]
Refactored
